<Project>
	<PropertyGroup>
		<Major>0</Major>
		<Minor>4</Minor>
		<Patch>1</Patch>
		<BuildNumber>695</BuildNumber>
		<ReleaseChannel>beta</ReleaseChannel>
		<ReleaseChannelNumber>0</ReleaseChannelNumber>
	<!--
		<VersionSuffix>alpha</VersionSuffix>
		<VersionSuffix>beta</VersionSuffix>
		<VersionSuffix>rc</VersionSuffix>
		<VersionSuffix>preview</VersionSuffix>
		<VersionSuffix>dev</VersionSuffix>
		<VersionSuffix>exp</VersionSuffix>
	-->

		<VersionPrefix>$(Major).$(Minor).$(Patch).$(BuildNumber)</VersionPrefix>
		<VersionSuffix>$(ReleaseChannel)$(ReleaseChannelNumber)</VersionSuffix>
	</PropertyGroup>
</Project>
