using BMTP3.Core4.Models.Enums;

namespace BMTP3.Core4.Models;

/// <summary>
/// Represents a single item known to a backup session.
/// </summary>
internal sealed class BackupItem : IBackupItem
{
	public BackupItem(IContent content)
	{
		Content = content ?? throw new ArgumentNullException(nameof(content));
	}

	/// <summary>
	/// Unique identifier for this item within the backup session.
	/// <para>
	/// For media devices, this may be a device-provided object id.
	/// For file system sources, this may be generated by the scanner.
	/// </para>
	/// </summary>
	public required string Id { get; init; } = string.Empty;
	
	/// <summary>
	/// The full original source path of the item.
	/// <para>
	/// This is the path used to locate the item in its original source system.
	/// </para>
	/// <para>
	/// Examples:
	/// <c>C:\Users\John\Pictures\image.jpg</c>,
	/// <c>\\NAS\Share\image.jpg</c>,
	/// <c>mtp://Apple iPad/Internal Storage/DCIM/image.jpg</c>.
	/// </para>
	/// </summary>
	public required string SourcePath { get; init; } = string.Empty;

	/// <summary>
	/// The path of the item relative to the configured backup source root.
	/// <para>
	/// This value represents the item's location inside the selected source tree
	/// and can be used when preserving the source folder structure at the destination.
	/// </para>
	/// <para>
	/// Example:
	/// If the configured source is <c>C:\Photos</c> and the file is
	/// <c>C:\Photos\2026\IMG_001.jpg</c>, the relative path may be
	/// <c>2026\IMG_001.jpg</c>.
	/// </para>
	/// </summary>
	public required string RelativeFilePath { get; init; } = string.Empty;

	/// <summary>
	/// The file name of the source item, including extension.
	/// <para>
	/// Example: <c>IMG_001.jpg</c>.
	/// </para>
	/// </summary>
	public required string FileName { get; init; } = string.Empty;
	
	/// <summary>
	/// The content of the backup item.
	/// <para>
	/// Must be replaced when the item's content location changes.
	/// </para>
	/// <para>
	/// May implement <see cref="IMoveableContent"/>.
	/// </para>
	/// </summary>
	public IContent Content { get; private set; }

	/// <summary>
	/// The source item creation date, if available.
	/// <para>
	/// For file system sources, this typically maps to file creation time.
	/// For MTP sources, this typically maps to <c>CreationTime</c>.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateCreated { get; set; }

	/// <summary>
	/// The source item last modified date, if available.
	/// <para>
	/// For file system sources, this typically maps to last write time.
	/// For MTP sources, this typically maps to <c>LastWriteTime</c>.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateModified { get; set; }

	/// <summary>
	/// The source item authored date, if available.
	/// <para>
	/// For media files, this may represent when the content was originally captured or authored.
	/// For MTP sources, this typically maps to <c>DateAuthored</c>.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateAuthored { get; set; }

	/// <summary>
	/// The source item last accessed date, if available.
	/// <para>
	/// Not all source types provide this value.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateAccessed { get; set; }

	/// <summary>
	/// Replaces the content provider for this backup item.
	/// <para>
	/// Must be called when the item's content location changes.
	/// </para>
	/// <para>
	/// The new provider may implement <see cref="IMoveableContent"/>.
	/// </para>
	/// </summary>
	public void ReplaceContentProvider(IContent content)
	{
		Content = content ?? throw new ArgumentNullException(nameof(content));
	}
}