using BMTP3.Core4.Models.Enums;

namespace BMTP3.Core4.Models;

/// <summary>
/// Represents a single item known to a backup session.
/// </summary>
internal sealed class BackupItem : IBackupItem
{
	public BackupItem(IContent content)
	{
		Content = content ?? throw new ArgumentNullException(nameof(content));
	}

	/// <summary>
	/// Unique identifier for this item within the backup session.
	/// <para>
	/// For media devices, this may be a device-provided object id.
	/// For file system sources, this may be generated by the scanner.
	/// </para>
	/// </summary>
	public required string Id { get; init; } = string.Empty;

	/// <summary>
	/// The original source path of the item.
	/// <para>
	/// Examples:
	/// <c>C:\Users\John\Pictures\image.jpg</c>,
	/// <c>\\NAS\Share\image.jpg</c>,
	/// <c>mtp://Apple iPad/Internal Storage/DCIM/image.jpg</c>.
	/// </para>
	/// </summary>
	public required string SourcePath { get; init; } = string.Empty;

	/// <summary>
	/// The path of the item relative to the configured backup source.
	/// </summary>
	public required string RelativePath { get; init; } = string.Empty;

	public required string FileName { get; init; } = string.Empty;

	/// <summary>
	/// The content of the backup item.
	/// </summary>
	public IContent Content { get; private set; }


	/// <summary>
	/// The source item creation date, if available.
	/// <para>
	/// For file system sources, this typically maps to file creation time.
	/// For MTP sources, this typically maps to <c>CreationTime</c>.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateCreated { get; set; }

	/// <summary>
	/// The source item last modified date, if available.
	/// <para>
	/// For file system sources, this typically maps to last write time.
	/// For MTP sources, this typically maps to <c>LastWriteTime</c>.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateModified { get; set; }

	/// <summary>
	/// The source item authored date, if available.
	/// <para>
	/// For media files, this may represent when the content was originally captured or authored.
	/// For MTP sources, this typically maps to <c>DateAuthored</c>.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateAuthored { get; set; }

	/// <summary>
	/// The source item last accessed date, if available.
	/// <para>
	/// Not all source types provide this value.
	/// </para>
	/// </summary>
	public DateTimeOffset? DateAccessed { get; set; }

	public void ReplaceContentProvider(IContent content)
	{
		Content = content ?? throw new ArgumentNullException(nameof(content));
	}
}