<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Models\Contexts\" />
		<Folder Include="DependencyInjection\" />
		<Folder Include="Progress\" />
		<Folder Include="Scanner\Filesystem\" />
		<Folder Include="Sidecar\" />
		<Folder Include="Transfer\Filesystem\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
		<PackageReference Include="Blake3" Version="2.2.1" />
		<PackageReference Include="MetadataExtractor" Version="2.9.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.7" />
		<PackageReference Include="SharpHash" Version="1.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BMTP3.Common\BMTP3.Common.csproj" />
	</ItemGroup>

</Project>

