<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <Version>$(VersionPrefix)</Version>
  </PropertyGroup>

	<!-- Release builds becomes automatically self-contained single exe -->
	<PropertyGroup Condition="'$(PublishProfile)' != ''">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="ExiftoolWrapper" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="SharpExifTool" Version="13.32.0.1" />
    <PackageReference Include="Spectre.Console" Version="0.57.1" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.9" />
    <PackageReference Include="Tomlyn" Version="2.9.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BMTP3.Core2\BMTP3.Core2.csproj" />
    <ProjectReference Include="..\BMTP3.Core3\BMTP3.Core3.csproj" />
    <ProjectReference Include="..\BMTP3.Core4\BMTP3.Core4.csproj" />
    <ProjectReference Include="..\BMTP3.Common\BMTP3.Common.csproj" />
  </ItemGroup>


	<ItemGroup>
		<Content Include="..\libs\MediaDevices.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
	</ItemGroup>
<!--
	<ItemGroup>
    <Reference Include="MediaDevices">
      <HintPath>..\libs\MediaDevices.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
-->

</Project>
