<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <Version>$(VersionPrefix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="exifreader\ExifReader.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="exifreader\ExifReader.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.Glob" Version="3.2.0-alpha.36" />
    <PackageReference Include="ExiftoolWrapper" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
    <PackageReference Include="SharpExifTool" Version="13.32.0.1" />
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BMTP3.Core2\BMTP3.Core2.csproj" />
    <ProjectReference Include="..\BMTP3.Core\BMTP3.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MediaDevices">
      <HintPath>..\..\..\GlobalPreussProjects\MediaDevices-FixErrors\Src\MediaDevices\bin\Release\net8.0-windows\MediaDevices.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
