<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BackupNew\Engine\Processor\**" />
    <Compile Remove="BackupNew\Reader\**" />
    <EmbeddedResource Remove="BackupNew\Engine\Processor\**" />
    <EmbeddedResource Remove="BackupNew\Reader\**" />
    <None Remove="BackupNew\Engine\Processor\**" />
    <None Remove="BackupNew\Reader\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MediaDevices">
	    <HintPath>..\libs\MediaDevices.dll</HintPath>
	    <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="ExiftoolWrapper" Version="5.2.0" />
    <PackageReference Include="MetadataExtractor" Version="2.9.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="SharpExifTool" Version="13.32.0.1" />
    <PackageReference Include="SharpHash" Version="1.2.0" />
    <PackageReference Include="ZLogger" Version="2.5.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BMTP3.Common\BMTP3.Common.csproj" />
  </ItemGroup>

</Project>
