<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BackupNew\Reader\**" />
    <EmbeddedResource Remove="BackupNew\Reader\**" />
    <None Remove="BackupNew\Reader\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MediaDevices">
      <HintPath>..\..\..\GlobalPreussProjects\MediaDevices-FixErrors\Src\MediaDevices\bin\Release\net8.0-windows\MediaDevices.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blake3" Version="2.0.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="SharpHash" Version="1.2.0" />
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="10.0.1" />
    <PackageReference Include="ZLogger" Version="2.5.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BMTP3.Common\BMTP3.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BackupNew\Engine\Processor\" />
  </ItemGroup>

</Project>
