using System.CommandLine;
using BMTP3.Consoles.ConsoleCommands.Core4;

namespace BMTP3.Consoles.ConsoleCommands;

public class BackupConsoleCommand4InitConfig : BaseConsoleCommand
{
	private static readonly HashSet<string> SupportedExtensions = [".toml", ".json", ".json5"];

	public BackupConsoleCommand4InitConfig() : this(null)
	{ }

	private BackupConsoleCommand4InitConfig(
		InitConfigOptionsModel? initConfigOptions
	) : base("init-config", "Generate a default backup configuration file.", initConfigOptions ?? new InitConfigOptionsModel())
	{
		InitConfigOptions = initConfigOptions ?? new InitConfigOptionsModel();
	}

	private InitConfigOptionsModel InitConfigOptions { get; }

	public IServiceProvider? ServiceProvider { get; init; }

	protected override async Task<int> DoExecuteAsync(
		ParseResult parseResult,
		CancellationToken cancellationToken
	)
	{
		FileInfo? output = InitConfigOptions.Output;
		string path = ResolvePath(output);

		string ext = Path.GetExtension(path).ToLowerInvariant();
		if (!SupportedExtensions.Contains(ext))
		{
			await Console.Error.WriteLineAsync($"Unsupported format '{ext}'. Supported: .toml, .json, .json5");
			return 2;
		}

		if (File.Exists(path))
		{
			await Console.Error.WriteLineAsync($"'{path}' already exists. Delete it, use a different output path, or choose a different config filename.");
			return 1;
		}

		string content = ext switch
		{
			".toml" => GenerateTomlContent(),
			".json" => GenerateJsonContent(),
			".json5" => GenerateJson5Content(),
			_ => throw new InvalidOperationException("Unhandled extension")
		};

		await File.WriteAllTextAsync(path, content, cancellationToken);
		await Console.Out.WriteLineAsync($"Generated: {path}");
		return 0;
	}

	internal static string GenerateTomlContent()
	{
		return """
		       # Backup Configuration File (TOML)
		       # Generated by backup4 init-config

		       # Name of the backup job
		       name = "MyBackup"

		       [source]
		       # Source path: local path (C:\Photos) or MTP URI (mtp://Device/Path)
		       path = "C:\\Path\\To\\Source"
		       # Include subdirectories
		       recursive = true
		       # Glob patterns to include
		       include-patterns = ["*.jpg", "*.png"]
		       # Glob patterns to exclude
		       exclude-patterns = ["*.tmp", "*.log"]

		       [destination]
		       # Output directory path
		       path = "D:\\Backup"
		       # Output structure: preserve-hierarchy, flat, custom-path-pattern
		       output-structure = "preserve-hierarchy"
		       # Custom path pattern (used when output-structure = custom-path-pattern)
		       custom-output-pattern = "{date}\\{filename}"

		       [collision]
		       # Collision strategy: rename, skip, overwrite, error
		       strategy = "rename"
		       # Collision comparison: none, hash, binary, size-and-modified-time
		       comparison = "binary"
		       # Rename strategy: increment, timestamp, hash, custom-pattern
		       rename-strategy = "increment"
		       # Custom rename pattern (used when rename-strategy = custom-pattern)
		       custom-pattern = "{counter}_{filename}"

		       [metadata]
		       # Sidecar format: none, ini, json
		       sidecar-format = "ini"
		       # Backup index type: none, json, database
		       index-type = "none"
		       # Enable metadata extraction (EXIF, timestamps)
		       enable-metadata = false
		       # Enable original timestamp restoration
		       enable-timestamp-correction = true
		       # Post-write verification: none, hash
		       post-write-verification = "none"
		       # Hash algorithms for file comparison
		       comparison-hash-algorithms = ["sha256"]
		       # Hash algorithms for post-write verification
		       verification-hash-algorithms = ["sha256"]

		       [behavior]
		       # Simulate backup without writing files
		       dry-run = false
		       # Stop immediately on first error
		       stop-on-error = true
		       # Delay in milliseconds between items (-1=disabled, 0=fastest, >0=N ms)
		       delay = 0
		       # Resume behavior: abort, continue, restart
		       resume-behavior = "continue"
		       """;
	}

	internal static string GenerateJsonContent()
	{
		return """
		       {
		         "name": "MyBackup",
		         "source": {
		           "path": "C:\\Path\\To\\Source",
		           "recursive": true,
		           "includePatterns": ["*.jpg", "*.png"],
		           "excludePatterns": ["*.tmp", "*.log"]
		         },
		         "destination": {
		           "path": "D:\\Backup",
		           "outputStructure": "preserve-hierarchy",
		           "customOutputPattern": "{date}\\{filename}"
		         },
		         "collision": {
		           "strategy": "rename",
		           "comparison": "binary",
		           "renameStrategy": "increment",
		           "customPattern": "{counter}_{filename}"
		         },
		         "metadata": {
		           "sidecarFormat": "ini",
		           "indexType": "none",
		           "enableMetadata": false,
		           "enableTimestampCorrection": true,
		           "postWriteVerification": "none",
		           "comparisonHashAlgorithms": ["sha256"],
		           "verificationHashAlgorithms": ["sha256"]
		         },
		         "behavior": {
		           "dryRun": false,
		           "stopOnError": true,
		           "delay": 0,
		           "resumeBehavior": "continue"
		         }
		       }
		       """;
	}

	internal static string GenerateJson5Content()
	{
		return """
		       // Backup Configuration File (JSON5)
		       // Generated by backup4 init-config
		       {
		         // Job name
		         name: 'MyBackup'

		         source: {
		           // Source path: local path (C:\Photos) or MTP URI (mtp://Device/Path)
		           path: 'C:\\Path\\To\\Source'
		           // Include subdirectories
		           recursive: true
		           // Glob patterns to include
		           includePatterns: ['*.jpg', '*.png']
		           // Glob patterns to exclude
		           excludePatterns: ['*.tmp', '*.log']
		         }

		         destination: {
		           // Output directory path
		           path: 'D:\\Backup'
		           // Output structure: preserve-hierarchy, flat, custom-path-pattern
		           outputStructure: 'preserve-hierarchy'
		           // Custom path pattern (used when output-structure = custom-path-pattern)
		           customOutputPattern: '{date}\\{filename}'
		         }

		         collision: {
		           // Collision strategy: rename, skip, overwrite, error
		           strategy: 'rename'
		           // Collision comparison: none, hash, binary, size-and-modified-time
		           comparison: 'binary'
		           // Rename strategy: increment, timestamp, hash, custom-pattern
		           renameStrategy: 'increment'
		           // Custom rename pattern (used when rename-strategy = custom-pattern)
		           customPattern: '{counter}_{filename}'
		         }

		         metadata: {
		           // Sidecar format: none, ini, json
		           sidecarFormat: 'ini'
		           // Backup index type: none, json, database
		           indexType: 'none'
		           // Enable metadata extraction (EXIF, timestamps)
		           enableMetadata: false
		           // Enable original timestamp restoration
		           enableTimestampCorrection: true
		           // Post-write verification: none, hash
		           postWriteVerification: 'none'
		           // Hash algorithms for file comparison
		           comparisonHashAlgorithms: ['sha256']
		           // Hash algorithms for post-write verification
		           verificationHashAlgorithms: ['sha256']
		         }

		         behavior: {
		           // Simulate backup without writing files
		           dryRun: false
		           // Stop immediately on first error
		           stopOnError: true
		           // Delay in milliseconds between items (-1=disabled, 0=fastest, >0=N ms)
		           delay: 0
		           // Resume behavior: abort, continue, restart
		           resumeBehavior: 'continue'
		         }
		       }
		       """;
	}

	private static string ResolvePath(FileInfo? output)
	{
		if (output == null)
			return Path.Combine(Directory.GetCurrentDirectory(), "default.toml");

		if (output.FullName.EndsWith(Path.DirectorySeparatorChar) || Directory.Exists(output.FullName))
		{
			Directory.CreateDirectory(output.FullName);
			return Path.Combine(output.FullName, "default.toml");
		}

		string? dir = Path.GetDirectoryName(output.FullName);
		if (!string.IsNullOrEmpty(dir))
			Directory.CreateDirectory(dir);
		return output.FullName;
	}
}